from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (
    admin_dashboard_view,
    admin_reports_view,
    admin_sports_view,
    admin_create_match_view,
    admin_matches_view,
    admin_edit_match_view,
    admin_settle_match_view,
    admin_cancel_match_view,
    admin_audit_logs_view,
    admin_users_view,
    admin_user_detail_view,
    admin_user_ledger_view,
    admin_bet_detail_view,
    admin_user_update_view,
    admin_reset_user_password_view,
    admin_withdrawals_view,
    admin_withdrawal_process_view,
    admin_exchange_dashboard_view,
    admin_cashback_dashboard_view,
    admin_pricing_overrides_view,
    admin_odds_adjustment_view,
    admin_rewards_view,
    admin_create_reward_view,
    admin_edit_reward_view,
    admin_backups_view,
    admin_backup_download_view,
    home_view,
    register_view,
    login_view,
    logout_view,
    password_reset_request_view,
    password_reset_confirm_view,
    matches_view,
    match_detail_view,
    match_odds_poll_view,
    parlay_bet_view,
    parlay_history_view,
    wallet_view,
    wallet_deposit_view,
    wallet_withdraw_view,
    confirm_deposit_view,
    bet_history_view,
    exchange_place_order_view,
    exchange_cancel_order_view,
    exchange_cash_out_view,
    exchange_cash_out_preview_view,
    exchange_history_view,
)

app_name = 'web'

urlpatterns = [
    path('', home_view, name='home'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('password-reset/', password_reset_request_view, name='password_reset'),
    path('password-reset/confirm/', password_reset_confirm_view, name='password_reset_confirm'),
    path('matches/', matches_view, name='matches'),
    path('matches/<int:pk>/', match_detail_view, name='match_detail'),
    path('matches/<int:pk>/odds-poll/', match_odds_poll_view, name='match_odds_poll'),
    path('matches/<int:pk>/exchange/place/', exchange_place_order_view, name='exchange_place_order'),
    path('exchange/orders/<int:order_id>/cancel/', exchange_cancel_order_view, name='exchange_cancel_order'),
    path('exchange/orders/<int:order_id>/cash-out/', exchange_cash_out_view, name='exchange_cash_out'),
    path('exchange/orders/<int:order_id>/cash-out-preview/', exchange_cash_out_preview_view, name='exchange_cash_out_preview'),
    path('exchange/history/', exchange_history_view, name='exchange_history'),
    path('dashboard/', admin_dashboard_view, name='dashboard'),
    # NOTE: this custom admin section deliberately lives under `panel/`, not
    # `admin/`. Django's built-in admin is mounted at `admin/` in
    # config/urls.py and registers a catch-all view for anything under that
    # prefix (AdminSite.catch_all_view) — any URL starting with `admin/`
    # never reaches these views at all, it's silently swallowed by Django's
    # own admin and either redirects to /admin/login/ or 404s. This cost a
    # full custom admin section its reachability until caught by testing.
    # Keep this prefix as `panel/` (or anything other than `admin/`).
    path('panel/reports/', admin_reports_view, name='admin_reports'),
    path('panel/sports/', admin_sports_view, name='admin_sports'),
    path('panel/matches/', admin_matches_view, name='admin_matches'),
    path('panel/matches/create/', admin_create_match_view, name='admin_create_match'),
    path('panel/matches/<int:match_id>/edit/', admin_edit_match_view, name='admin_edit_match'),
    path('panel/matches/<int:match_id>/settle/', admin_settle_match_view, name='admin_settle_match'),
    path('panel/matches/<int:match_id>/cancel/', admin_cancel_match_view, name='admin_cancel_match'),
    path('panel/audit/', admin_audit_logs_view, name='admin_audit'),
    path('panel/users/', admin_users_view, name='admin_users'),
    path('panel/users/<int:user_id>/', admin_user_detail_view, name='admin_user_detail'),
    path('panel/users/<int:user_id>/ledger/', admin_user_ledger_view, name='admin_user_ledger'),
    path('panel/bets/<int:bet_id>/', admin_bet_detail_view, name='admin_bet_detail'),
    path('panel/users/<int:user_id>/edit/', admin_user_update_view, name='admin_user_edit'),
    path('panel/users/<int:user_id>/reset-password/', admin_reset_user_password_view, name='admin_reset_user_password'),
    path('panel/withdrawals/', admin_withdrawals_view, name='admin_withdrawals'),
    path('panel/withdrawals/<int:payment_id>/process/', admin_withdrawal_process_view, name='admin_withdrawal_process'),
    path('panel/exchange/', admin_exchange_dashboard_view, name='admin_exchange'),
    path('panel/cashback/', admin_cashback_dashboard_view, name='admin_cashback'),
    path('panel/pricing-overrides/', admin_pricing_overrides_view, name='admin_pricing_overrides'),
    path('panel/odds-adjustment/', admin_odds_adjustment_view, name='admin_odds_adjustment'),
    path('panel/rewards/', admin_rewards_view, name='admin_rewards'),
    path('panel/rewards/create/', admin_create_reward_view, name='admin_create_reward'),
    path('panel/rewards/<int:package_id>/edit/', admin_edit_reward_view, name='admin_edit_reward'),
    path('panel/backups/', admin_backups_view, name='admin_backups'),
    path('panel/backups/<str:filename>/download/', admin_backup_download_view, name='admin_backup_download'),
    path('parlay/', parlay_bet_view, name='parlay_bet'),
    path('parlays/', parlay_history_view, name='parlay_history'),
    path('wallet/', wallet_view, name='wallet'),
    path('wallet/deposit/', wallet_deposit_view, name='wallet_deposit'),
    path('wallet/withdraw/', wallet_withdraw_view, name='wallet_withdraw'),
    path('wallet/confirm-deposit/<int:deposit_id>/', confirm_deposit_view, name='confirm_deposit'),
    path('bets/', bet_history_view, name='bets'),
]
