# Generated by Django 5.2 on 2026-09-07 01:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Cashback enabled (global default)')),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99'))], verbose_name='Default cashback rate (%) on net losses')),
                ('default_wagering_multiplier', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='Default wagering multiplier (0 = immediately withdrawable)')),
                ('deduct_original_on_unlock', models.BooleanField(default=False, verbose_name='Deduct original cashback amount when the wagering requirement clears')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cashback Config',
                'verbose_name_plural': 'Cashback Config',
            },
        ),
        migrations.CreateModel(
            name='CashbackCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_description', models.CharField(max_length=255)),
                ('loss_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rate_applied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cashback_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('multiplier_applied', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wagering_required', models.DecimalField(decimal_places=8, max_digits=20)),
                ('wagering_progress', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('deduct_original_on_unlock', models.BooleanField()),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked')], default='locked', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashback Credit',
                'verbose_name_plural': 'Cashback Credits',
                'ordering': ['-created_at'],
            },
        ),
    ]
