# Generated by Django 5.2 on 2026-09-07 02:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deposit_threshold', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Cumulative lifetime deposit required')),
                ('commission_rate_bonus', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99'))], verbose_name='Commission rate (%) bonus added permanently when earned')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward Package',
                'verbose_name_plural': 'Reward Packages',
                'ordering': ['deposit_threshold'],
            },
        ),
        migrations.CreateModel(
            name='UserRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate_bonus_applied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deposit_total_at_claim', models.DecimalField(decimal_places=8, max_digits=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='rewards.rewardpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Reward Claim',
                'verbose_name_plural': 'User Reward Claims',
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'package')},
            },
        ),
    ]
