# Generated by Django 5.2 on 2026-09-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cashback_enabled_override',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cashback enabled (blank = inherit global setting)'),
        ),
        migrations.AddField(
            model_name='user',
            name='cashback_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cashback rate % override (blank = inherit global default)'),
        ),
        migrations.AddField(
            model_name='user',
            name='cashback_wagering_multiplier_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Cashback wagering multiplier override (blank = inherit global default)'),
        ),
    ]
