# Generated by Django 5.2 on 2026-09-07 02:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_cashback_enabled_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cashback_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99'))], verbose_name='Cashback rate % override (blank = inherit global default)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cashback_wagering_multiplier_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='Cashback wagering multiplier override (blank = inherit global default)'),
        ),
    ]
