# Generated by Django 5.2 on 2026-09-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_cashback_rate_override_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_house_account',
            field=models.BooleanField(default=False, verbose_name='House account (the exchange auto-seeds synthetic lay liquidity as this user)'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_house_account', True)), fields=('is_house_account',), name='at_most_one_house_account'),
        ),
    ]
