# Generated by Django 5.2 on 2026-09-07 17:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_user_is_house_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='odds_adjustment_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-10.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Odds adjustment override for this user, all matches (blank = no extra change)'),
        ),
    ]
