# Generated by Django 5.2 on 2026-09-07 21:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_odds_adjustment_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='odds_adjustment_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-99.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))], verbose_name='Odds adjustment override for this user, all matches (blank = no extra change)'),
        ),
    ]
