# Generated by Django 5.2 on 2026-09-07 23:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_odds_adjustment_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lay_spread_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Lay-reference spread override for this user, all matches (blank = no extra change; sportsbook display only, never the exchange)'),
        ),
    ]
