# Generated by Django 5.2 on 2026-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_lay_spread_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Country (ISO code, collected at signup)'),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR')], default='USD', max_length=3, verbose_name='Wallet currency - derived from country at signup (PK -> PKR, everything else -> USD) and never changed afterward; every deposit, withdrawal, bet, and balance for this user is denominated in this currency.'),
        ),
    ]
