# Generated by Django 5.2 on 2026-09-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_placed', 'Bet Placed'), ('bet_won', 'Bet Won'), ('bet_refund', 'Bet Refund'), ('commission', 'Commission'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
