# Generated by Django 5.2 on 2026-09-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallettransaction_txn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_placed', 'Bet Placed'), ('bet_won', 'Bet Won'), ('bet_refund', 'Bet Refund'), ('commission', 'Commission'), ('adjustment', 'Adjustment'), ('exchange_won', 'Exchange Won'), ('exchange_lost', 'Exchange Lost')], max_length=20),
        ),
    ]
