# Generated by Django 5.2 on 2026-09-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallettransaction_txn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='locked_cashback_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_placed', 'Bet Placed'), ('bet_won', 'Bet Won'), ('bet_refund', 'Bet Refund'), ('commission', 'Commission'), ('adjustment', 'Adjustment'), ('exchange_won', 'Exchange Won'), ('exchange_lost', 'Exchange Lost'), ('cashback_credit', 'Cashback Credit'), ('cashback_clawback', 'Cashback Clawback')], max_length=20),
        ),
    ]
