# Generated by Django 5.2 on 2026-09-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_locked_cashback_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_placed', 'Bet Placed'), ('bet_won', 'Bet Won'), ('bet_refund', 'Bet Refund'), ('commission', 'Commission'), ('adjustment', 'Adjustment'), ('exchange_won', 'Exchange Won'), ('exchange_lost', 'Exchange Lost'), ('cashback_credit', 'Cashback Credit'), ('cashback_clawback', 'Cashback Clawback'), ('casino_session_open', 'Casino Session Open'), ('casino_win', 'Casino Win')], max_length=20),
        ),
    ]
