# Generated by Django 5.2 on 2026-09-09 08:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallettransaction_txn_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_pkr_rate', models.DecimalField(decimal_places=4, default=Decimal('280.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.0000')), django.core.validators.MaxValueValidator(Decimal('10000.0000'))], verbose_name="USD -> PKR rate (used for every PKR-currency user's deposits/withdrawals/balance)")),
                ('is_manual_override', models.BooleanField(default=False, verbose_name='Manual override (when on, the hourly live-rate refresh is skipped and this rate is used as-is)')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FX Rate Config',
                'verbose_name_plural': 'FX Rate Config',
            },
        ),
    ]
