# Generated by Django 5.2 on 2026-09-08 01:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('game_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Casino Brand',
                'verbose_name_plural': 'Casino Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CasinoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Casino enabled (players can launch real-money games)')),
                ('max_launch_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='Max balance (USD) a single game launch may hand over')),
                ('usd_to_pkr_rate', models.DecimalField(decimal_places=4, default=Decimal('278.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.0000')), django.core.validators.MaxValueValidator(Decimal('10000.0000'))], verbose_name="USD -> PKR conversion rate used for Pakistani players' game balance/currency_code")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Casino Config',
                'verbose_name_plural': 'Casino Config',
            },
        ),
        migrations.CreateModel(
            name='CasinoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.PositiveIntegerField()),
                ('game_uid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='casino.casinobrand')),
            ],
            options={
                'verbose_name': 'Casino Game',
                'verbose_name_plural': 'Casino Games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CasinoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_balance_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('opened_balance_provider_currency', models.DecimalField(decimal_places=8, max_digits=20)),
                ('provider_currency_code', models.CharField(max_length=10)),
                ('fx_rate_applied', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='casino.casinogame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Casino Session',
                'verbose_name_plural': 'Casino Sessions',
                'ordering': ['-launched_at'],
            },
        ),
        migrations.CreateModel(
            name='CasinoRoundSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_serial_number', models.CharField(max_length=255, unique=True)),
                ('bet_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('win_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('credit_amount_reported', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_settlements', to='casino.casinosession')),
            ],
            options={
                'verbose_name': 'Casino Round Settlement',
                'verbose_name_plural': 'Casino Round Settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
