# Generated by Django 5.2 on 2026-09-08 02:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casinoconfig',
            name='usd_to_pkr_rate',
        ),
        migrations.AddField(
            model_name='casinoconfig',
            name='provider_currency_code',
            field=models.CharField(default='USD', max_length=10, verbose_name='Currency code sent to the casino provider (must match what the provider account actually supports - confirmed 2026-09-08 that the account is fixed to USD, not admin-selectable per launch)'),
        ),
        migrations.AddField(
            model_name='casinoconfig',
            name='usd_to_provider_currency_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('10000.0000'))], verbose_name='USD -> provider_currency_code conversion rate (1.0000 when provider_currency_code is USD)'),
        ),
    ]
