# Generated by Django 5.2 on 2026-09-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0002_remove_casinoconfig_usd_to_pkr_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinoconfig',
            name='use_proxy',
            field=models.BooleanField(default=False, verbose_name='Route game traffic through the casino proxy (backend/casino_proxy) instead of redirecting players straight to the provider - fixes lag/pixelation on poorly-routed connections. Off by default: same safe-until-opted-in posture as is_enabled.'),
        ),
    ]
