# Generated by Django 5.2 on 2026-09-08 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0003_casinoconfig_use_proxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casinoconfig',
            name='use_proxy',
        ),
        migrations.CreateModel(
            name='CasinoWalletEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('action', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('round_id', models.CharField(blank=True, default='', max_length=255)),
                ('game_uid', models.CharField(blank=True, default='', max_length=50)),
                ('event_type', models.CharField(blank=True, default='', max_length=30)),
                ('is_rollback', models.BooleanField(default=False)),
                ('cash_skipped', models.BooleanField(default=False, verbose_name='True for a free-round (bonus_fs) debit that never touched real cash')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_wallet_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Casino Wallet Event',
                'verbose_name_plural': 'Casino Wallet Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
