# Generated by Django 5.2 on 2026-09-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0004_remove_casinoconfig_use_proxy_casinowalletevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinogame',
            name='game_uid',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
