# Generated by Django 5.2 on 2026-09-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0005_alter_casinogame_game_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinowalletevent',
            name='game_uid',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
