# Generated by Django 5.2 on 2026-09-08 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0006_alter_casinowalletevent_game_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinowalletevent',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_events', to='casino.casinogame', verbose_name='Resolved from game_uid at write time, for admin/ledger display - never used for money math itself.'),
        ),
    ]
