# Generated by Django 5.2 on 2026-09-09 08:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0007_casinowalletevent_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinosession',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Amount actually debited from the wallet, in wallet_currency (see apps.wallet.services.convert_usd_to_wallet_currency) - distinct from opened_balance_provider_currency, which is the Waija/SoftAPI account-currency conversion, a separate concern'),
        ),
        migrations.AddField(
            model_name='casinosession',
            name='wallet_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='casinosession',
            name='wallet_fx_rate_applied',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='casinowalletevent',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Amount actually applied to wallet.balance, in wallet_currency (see apps.wallet.services.convert_usd_to_wallet_currency)'),
        ),
        migrations.AddField(
            model_name='casinowalletevent',
            name='wallet_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='casinowalletevent',
            name='wallet_fx_rate_applied',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='casinowalletevent',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name="Raw amount as reported by the provider, in the provider account currency (USD today) - kept unchanged for reconciliation against the provider's own dashboard; see wallet_amount for what was actually applied to the wallet"),
        ),
    ]
