# Generated by Django 5.2 on 2026-09-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0008_casinosession_wallet_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinogame',
            name='blur_region',
            field=models.JSONField(blank=True, null=True, verbose_name='Thumbnail blur region ({top, left, width, height}, all percentages of the image) - admin-set per game via admin_casino_game_blur_view; None means no blur. Never touched by sync_catalog, same "admin curation survives a re-sync" pattern as is_active.'),
        ),
    ]
