# Generated by Django 5.2 on 2026-09-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0009_casinogame_blur_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinogame',
            name='live_blur_region',
            field=models.JSONField(blank=True, null=True, verbose_name='Persistent in-play blur region ({top, left, width, height}, percentages of the iframe area) - a fixed overlay shown for the whole session on a live-dealer game with a female host, covering her face/upper costume. Set via admin_casino_game_live_blur_view against the free demo stream (no way to auto-detect this - the actual video is inside a cross-origin iframe we cannot read pixels from, so this is a manually-positioned fixed box, not real-time tracking). None means no overlay. Never touched by sync_catalog.'),
        ),
    ]
