# Generated by Django 5.2 on 2026-09-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0010_casinogame_live_blur_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinogame',
            name='ai_tracking_enabled',
            field=models.BooleanField(default=False, verbose_name='Opt this game into the live AI face-tracking watcher (apps.casino.management.commands.run_ai_blur_tracker) instead of (or alongside) the fixed live_blur_region. The watcher only runs for a game while at least one player currently has it open - see docs/BLUR_DOCUMENTATION.md Section 3.'),
        ),
        migrations.AddField(
            model_name='casinogame',
            name='detected_blur_region',
            field=models.JSONField(blank=True, null=True, verbose_name='Live AI-detected blur region ({top, left, width, height}, percentages of the iframe area) - written continuously by the AI tracker watcher while it is actively watching this game, read by casino_wallet_status_view. Only trusted if detected_blur_region_updated_at is recent (see AI_TRACKING_STALE_AFTER_SECONDS in services.py) - otherwise callers must fall back to the fixed live_blur_region rather than show no blur at all.'),
        ),
        migrations.AddField(
            model_name='casinogame',
            name='detected_blur_region_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casinogame',
            name='live_blur_region',
            field=models.JSONField(blank=True, null=True, verbose_name='Persistent in-play blur region ({top, left, width, height}, percentages of the iframe area) - a fixed overlay shown for the whole session on a live-dealer game with a female host, covering her face/upper costume. Set via admin_casino_game_live_blur_view against the free demo stream (no way to auto-detect this - the actual video is inside a cross-origin iframe we cannot read pixels from, so this is a manually-positioned fixed box, not real-time tracking). None means no overlay. Never touched by sync_catalog. Used as the safety fallback whenever ai_tracking_enabled is on but no fresh detected_blur_region is available - see docs/BLUR_DOCUMENTATION.md Section 3.'),
        ),
    ]
