# Generated by Django 5.2 on 2026-09-10 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0011_casinogame_ai_tracking_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoLiveViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_viewers', to='casino.casinogame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_live_viewer_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Casino Live Viewer',
                'verbose_name_plural': 'Casino Live Viewers',
                'constraints': [models.UniqueConstraint(fields=('user', 'game'), name='unique_casino_live_viewer_per_user_game')],
            },
        ),
    ]
