import io
from datetime import datetime

from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings
from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError

# Excluded from the dump because they're regenerated by Django itself (via
# post_migrate signals) rather than being real business data, and including
# them risks primary-key/foreign-key mismatches on restore into a freshly
# migrated database: contenttypes and auth.permission rows get new IDs on
# every `migrate`, admin.logentry references contenttype IDs that may no
# longer match, and sessions are ephemeral and worthless to restore anyway.
EXCLUDED_MODELS = ['contenttypes', 'auth.permission', 'admin.logentry', 'sessions.session']


class Command(BaseCommand):
    help = (
        'Dump the entire database (every user, wallet, bet, match and audit '
        'record - everything except ephemeral/regenerated tables) to a single '
        'JSON fixture, encrypt it with BACKUP_ENCRYPTION_KEY, and write it to '
        'BACKUP_DIR as a timestamped .json.enc file. Older backups beyond the '
        'retention count are then deleted.'
    )

    def add_arguments(self, parser):
        parser.add_argument(
            '--keep', type=int, default=14,
            help='Number of most-recent backup files to retain (default: 14).',
        )

    def handle(self, *args, **options):
        key = settings.BACKUP_ENCRYPTION_KEY
        if not key:
            raise CommandError(
                'BACKUP_ENCRYPTION_KEY is not set. Generate one with: '
                'python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" '
                'and set it in .env.'
            )
        try:
            fernet = Fernet(key.encode())
        except (ValueError, InvalidToken) as exc:
            raise CommandError(f'BACKUP_ENCRYPTION_KEY is not a valid Fernet key: {exc}')

        buffer = io.StringIO()
        call_command(
            'dumpdata',
            natural_foreign=True,
            natural_primary=True,
            exclude=EXCLUDED_MODELS,
            indent=2,
            stdout=buffer,
        )
        plaintext = buffer.getvalue().encode('utf-8')
        encrypted = fernet.encrypt(plaintext)

        settings.BACKUP_DIR.mkdir(parents=True, exist_ok=True)
        # Microsecond precision, not just seconds - two backups triggered
        # close together (e.g. a double-clicked "Trigger backup now") must
        # never land on the same filename and silently overwrite each other.
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S_%f')
        filename = f'backup_{timestamp}.json.enc'
        filepath = settings.BACKUP_DIR / filename
        filepath.write_bytes(encrypted)

        removed = self._prune_old_backups(options['keep'])

        self.stdout.write(self.style.SUCCESS(f'Backup written: {filepath} ({len(encrypted)} bytes)'))
        if removed:
            self.stdout.write(f'Pruned {len(removed)} old backup(s): {", ".join(removed)}')

        return str(filepath)

    def _prune_old_backups(self, keep: int) -> list:
        backups = sorted(settings.BACKUP_DIR.glob('backup_*.json.enc'), key=lambda p: p.name)
        to_remove = backups[:-keep] if keep > 0 else backups
        removed_names = []
        for path in to_remove:
            path.unlink()
            removed_names.append(path.name)
        return removed_names
