# Generated by Django 5.2 on 2026-09-07 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_sport_provider_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeOddsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Real-time odds refresh enabled (global switch)')),
                ('live_refresh_seconds', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Refresh interval (seconds) for live/in-play matches')),
                ('not_started_refresh_seconds', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3600)], verbose_name='Refresh interval (seconds) for matches that have not started yet')),
                ('proximity_boost_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)], verbose_name='Refresh interval (seconds) once a match is close to starting')),
                ('proximity_window_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)], verbose_name='How close to start time (minutes) counts as "close enough" for the boosted interval')),
                ('min_viewers_for_realtime', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Minimum concurrent viewers on a match before its odds refresh in real time')),
                ('bet_acceptance_delay_seconds', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Odds re-validation window (seconds) at bet placement')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Realtime Odds Config',
                'verbose_name_plural': 'Realtime Odds Config',
            },
        ),
    ]
