# Generated by Django 5.2 on 2026-09-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_realtimeoddsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeoddsconfig',
            name='store_full_odds_history',
            field=models.BooleanField(default=False, verbose_name='Keep a full history row every time odds refresh (off = only the latest value is kept, on Match itself)'),
        ),
        migrations.CreateModel(
            name='OddsHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_home', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_away', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_history', to='sports.match')),
            ],
            options={
                'verbose_name': 'Odds History Entry',
                'verbose_name_plural': 'Odds History Entries',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
