# Generated by Django 5.2 on 2026-09-07 07:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_realtimeoddsconfig_store_full_odds_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddsAdjustmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-10.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name="Default odds adjustment (added to every match's odds unless a match overrides it)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Odds Adjustment Config',
                'verbose_name_plural': 'Odds Adjustment Config',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='odds_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-10.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Odds adjustment override (added to every odds value; blank = use the global default)'),
        ),
    ]
