# Generated by Django 5.2 on 2026-09-07 13:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_oddsadjustmentconfig_match_odds_adjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLiquidityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='House lay-liquidity seeding enabled (global switch)')),
                ('default_lay_spread', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Default back→lay spread (flat amount added to the back odds to get the house lay price)')),
                ('default_max_liability_per_selection', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Default max house liability (currency units) per match+selection')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'House Liquidity Config',
                'verbose_name_plural': 'House Liquidity Config',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='house_max_liability_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Max house liability per selection override for this match (blank = use the global default)'),
        ),
        migrations.AddField(
            model_name='match',
            name='lay_spread_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Back→lay spread override for house-seeded exchange liquidity (blank = use the global default)'),
        ),
    ]
