# Generated by Django 5.2 on 2026-09-07 17:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_houseliquidityconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchOddsOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-10.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Odds adjustment for this user on this match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_odds_overrides', to='sports.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_odds_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User/Match Odds Override',
                'verbose_name_plural': 'User/Match Odds Overrides',
                'unique_together': {('user', 'match')},
            },
        ),
    ]
