# Generated by Django 5.2 on 2026-09-07 18:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_usermatchoddsoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='houseliquidityconfig',
            name='default_back_custom_value_away',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Default custom back value, Away (used when default_back_mode = custom)'),
        ),
        migrations.AddField(
            model_name='houseliquidityconfig',
            name='default_back_custom_value_draw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Default custom back value, Draw (used when default_back_mode = custom)'),
        ),
        migrations.AddField(
            model_name='houseliquidityconfig',
            name='default_back_custom_value_home',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Default custom back value, Home (used when default_back_mode = custom)'),
        ),
        migrations.AddField(
            model_name='houseliquidityconfig',
            name='default_back_mode',
            field=models.CharField(choices=[('api', 'API (genuine Pinnacle price)'), ('custom', 'Custom (frozen admin value)')], default='api', max_length=10, verbose_name='Default back price mode (global)'),
        ),
        migrations.AddField(
            model_name='houseliquidityconfig',
            name='default_lay_custom_value_away',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Default custom lay value, Away (used when default_lay_mode = custom)'),
        ),
        migrations.AddField(
            model_name='houseliquidityconfig',
            name='default_lay_custom_value_draw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Default custom lay value, Draw (used when default_lay_mode = custom)'),
        ),
        migrations.AddField(
            model_name='houseliquidityconfig',
            name='default_lay_custom_value_home',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Default custom lay value, Home (used when default_lay_mode = custom)'),
        ),
        migrations.AddField(
            model_name='houseliquidityconfig',
            name='default_lay_mode',
            field=models.CharField(choices=[('api_lay', 'API Lay (back + house spread)'), ('relative', 'Relative Lay (back + custom delta)'), ('custom', 'Custom Lay (independent fixed value)')], default='api_lay', max_length=10, verbose_name='Default lay price mode (global)'),
        ),
        migrations.AddField(
            model_name='houseliquidityconfig',
            name='default_lay_relative_delta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-10.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name="Default relative lay delta (used when default_lay_mode = relative; same delta applied to each selection's own back)"),
        ),
        migrations.CreateModel(
            name='PricingOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_mode', models.CharField(choices=[('api', 'API (genuine Pinnacle price)'), ('custom', 'Custom (frozen admin value)')], default='api', max_length=10)),
                ('back_custom_value_home', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Custom back value, Home (used when back_mode = custom)')),
                ('back_custom_value_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Custom back value, Draw (used when back_mode = custom)')),
                ('back_custom_value_away', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Custom back value, Away (used when back_mode = custom)')),
                ('lay_mode', models.CharField(choices=[('api_lay', 'API Lay (back + house spread)'), ('relative', 'Relative Lay (back + custom delta)'), ('custom', 'Custom Lay (independent fixed value)')], default='api_lay', max_length=10)),
                ('lay_relative_delta', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-10.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name="Relative lay delta (used when lay_mode = relative; same delta applied to each selection's own back)")),
                ('lay_custom_value_home', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Custom lay value, Home (used when lay_mode = custom)')),
                ('lay_custom_value_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Custom lay value, Draw (used when lay_mode = custom)')),
                ('lay_custom_value_away', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Custom lay value, Away (used when lay_mode = custom)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_overrides', to='sports.match', verbose_name='Match (blank = applies to all matches)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_overrides', to=settings.AUTH_USER_MODEL, verbose_name='User (blank = applies to all users)')),
            ],
            options={
                'verbose_name': 'Pricing Override (Custom Odds)',
                'verbose_name_plural': 'Pricing Overrides (Custom Odds)',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('match',), name='at_most_one_match_only_pricing_override'), models.UniqueConstraint(condition=models.Q(('match__isnull', True)), fields=('user',), name='at_most_one_user_only_pricing_override')],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
