# Generated by Django 5.2 on 2026-09-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_houseliquidityconfig_default_back_custom_value_away_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='refresh_mode_override',
            field=models.CharField(blank=True, choices=[('viewer_gated', 'Viewer-gated (default) - refresh on schedule only when enough viewers are watching'), ('always', 'Always - refresh on schedule regardless of viewer count'), ('manual_only', 'Manual only - never auto-refresh, only when explicitly triggered'), ('stopped', 'Stopped - fully frozen, no refresh at all (even manual)')], max_length=15, null=True, verbose_name='Refresh mode override for this match (blank = use the global default)'),
        ),
        migrations.AddField(
            model_name='realtimeoddsconfig',
            name='default_refresh_mode',
            field=models.CharField(choices=[('viewer_gated', 'Viewer-gated (default) - refresh on schedule only when enough viewers are watching'), ('always', 'Always - refresh on schedule regardless of viewer count'), ('manual_only', 'Manual only - never auto-refresh, only when explicitly triggered'), ('stopped', 'Stopped - fully frozen, no refresh at all (even manual)')], default='viewer_gated', max_length=15, verbose_name='Default refresh mode (global)'),
        ),
    ]
