# Generated by Django 5.2 on 2026-09-07 21:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_match_refresh_mode_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseliquidityconfig',
            name='default_lay_relative_delta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-99.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))], verbose_name="Default relative lay delta (used when default_lay_mode = relative; same delta applied to each selection's own back)"),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-99.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))], verbose_name='Odds adjustment override (added to every odds value; blank = use the global default)'),
        ),
        migrations.AlterField(
            model_name='oddsadjustmentconfig',
            name='default_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-99.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))], verbose_name="Default odds adjustment (added to every match's odds unless a match overrides it)"),
        ),
        migrations.AlterField(
            model_name='pricingoverride',
            name='lay_relative_delta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-99.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))], verbose_name="Relative lay delta (used when lay_mode = relative; same delta applied to each selection's own back)"),
        ),
        migrations.AlterField(
            model_name='usermatchoddsoverride',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-99.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))], verbose_name='Odds adjustment for this user on this match'),
        ),
    ]
