# Generated by Django 5.2 on 2026-09-07 23:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_alter_houseliquidityconfig_default_lay_relative_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermatchoddsoverride',
            name='lay_spread_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Lay-reference spread for this user on this match (blank = no extra change; sportsbook display only)'),
        ),
        migrations.AlterField(
            model_name='usermatchoddsoverride',
            name='adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-99.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))], verbose_name='Odds adjustment for this user on this match (blank = no extra change to odds)'),
        ),
    ]
