# Generated by Django 5.2 on 2026-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopayment',
            name='fx_rate_applied',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='USD -> wallet_currency rate snapshotted at request time (1.0000 for a USD wallet)'),
        ),
        migrations.AddField(
            model_name='cryptopayment',
            name='wallet_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Amount actually credited/debited on the wallet, in wallet_currency (equals `amount` for a USD wallet; converted via fx_rate_applied for a PKR wallet)'),
        ),
        migrations.AddField(
            model_name='cryptopayment',
            name='wallet_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
