# Generated by Django 5.2 on 2026-09-06 20:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0002_sport_provider_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Commission rate (%) on exchange winnings')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Config',
                'verbose_name_plural': 'Exchange Config',
            },
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('home', 'Home'), ('draw', 'Draw'), ('away', 'Away')], max_length=10)),
                ('side', models.CharField(choices=[('back', 'Back'), ('lay', 'Lay')], max_length=4)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stake', models.DecimalField(decimal_places=8, max_digits=20)),
                ('matched_stake', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('settled', 'Settled'), ('void', 'Void')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_orders', to='sports.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Order',
                'verbose_name_plural': 'Exchange Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('home', 'Home'), ('draw', 'Draw'), ('away', 'Away')], max_length=10)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stake', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('back_won', 'Back Won'), ('lay_won', 'Lay Won'), ('void', 'Void')], default='pending', max_length=20)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_fills', to='sports.match')),
                ('back_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='back_fills', to='exchange.exchangeorder')),
                ('lay_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lay_fills', to='exchange.exchangeorder')),
            ],
            options={
                'verbose_name': 'Exchange Fill',
                'verbose_name_plural': 'Exchange Fills',
                'ordering': ['-created_at'],
            },
        ),
    ]
